### ISSUE TITLE
There's an issue with sending certain types of BSV-20

### ISSUE THREAD

**Issue by danwag06** [yours-org/yours-wallet#118]
Wallet holding early inscriptions like PEPE will not send with error:

```
useOrds.ts:376 sendBSV20 failed: Error: doesn't contains any inscription!
    at getBsv20v1 (ordi.ts:136:1)
    at getAmtv1 (ordi.ts:203:1)
    at useOrds.ts:296:1
    at Array.reduce (<anonymous>)
    at sendBSV20 (useOrds.ts:295:1)
    at async handleSendBSV20 (OrdWallet.tsx:273:1)
```

**Comment by danwag06** [comment]
@shruggr @zhfnjust I'm seeing this when trying to send the PEPE token
